# Generated by Django 4.0.3 on 2022-11-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='weather',
            field=models.IntegerField(null=True),
        ),
    ]
