# Generated by Django 4.0.3 on 2022-11-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_location_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
