# Generated by Django 4.0.3 on 2022-11-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_location_description_alter_conference_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='temp',
            field=models.IntegerField(null=True),
        ),
    ]
